
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\donsi\Desktop\MALFA\UNI\AÑO 3\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("600x400")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 600,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    300.0,
    200.0,
    image=image_image_1
)

canvas.create_rectangle(
    17.0,
    10.0,
    577.0,
    390.0,
    fill="#000000",
    outline="")

canvas.create_text(
    212.0,
    61.0,
    anchor="nw",
    text="Sube tus archivos y encriptalos aquí",
    fill="#606060",
    font=("KantumruyPro Medium", 10 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=182.0,
    y=129.0,
    width=237.0,
    height=38.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=181.0,
    y=233.0,
    width=237.0,
    height=38.0
)

canvas.create_text(
    76.0,
    39.0,
    anchor="nw",
    text="ENCRIPTACIÓN DE ARCHIVOS",
    fill="#601E88",
    font=("KantumruyPro Medium", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
